name: advanced_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  freezed: ^2.5.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  dio: ^5.4.0
  retrofit: ^4.4.2
  retrofit_generator: ^8.0.6
  pretty_dio_logger: ^1.4.0
  intl: ^0.19.0
  easy_localization: ^3.0.5
  flutter_native_splash: ^2.3.9
  flutter_svg: ^2.1.0
  flutter_screenutil: ^5.9.0
  intl_phone_field: ^3.2.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8

flutter_native_splash:
  # Splash screen image configuration
  image: assets/images/Frame 1000005357 (1).png
  # color: "#ffffff"  # Background color (white in this case)
  # If you want to use your background image instead of color, remove the color line and use:
  background_image: assets/images/BackGroundImage.png
  
  # Android configuration
  android: true
  android_gravity: center
  
  # iOS configuration
  ios: true
  ios_content_mode: center
  
  # Dark mode configuration (optional)
  # dark_mode_image: assets/images/Frame 1000005357 (1).png  # Optional dark mode image
  # dark_mode_color: "#121212"  # Optional dark mode background color

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Frame 1000005357 (1).png
    - assets/images/BackGroundImage.png